<script lang="ts">
    import ShareIcon from "$lib/components/icons/ShareIcon.svelte";
    import DialogModal from "$lib/components/modals/DialogModal.svelte";
    import Button from "$lib/components/Button.svelte";
    import {msg} from "$lib/i18n.svelte";

    type ConfigValue = string | string[];

    interface Props {
        parsedConfig: Record<string, ConfigValue> | null;
        previewText: string | null;
        parseError: boolean;
        onclose?: () => void | Promise<void>;
        onimport?: () => void | Promise<void>;
        keyFormatter?: (key: string) => string;
    }

    const {
        parsedConfig,
        previewText,
        parseError,
        onclose,
        onimport,
        keyFormatter = (key: string) => key
    }: Props = $props();
</script>

<DialogModal title={msg("Shared Config", "分享的配置")} {onclose}>
    {#snippet icon()}
        <ShareIcon />
    {/snippet}

    <p class="share-modal-desc">{msg("Someone shared a Ghostty config with you. Review it before importing.", "有人向你分享了一个 Ghostty 配置。导入前请先检查。")}</p>
    <div class="share-preview">
        {#if parsedConfig}
            <div class="row p2"># {msg("Config generated by Ghostty Config", "由 Ghostty 配置生成器生成的配置")}</div>
            <div class="row">&nbsp;</div>
            {#each Object.entries(parsedConfig) as [key, value], i (i)}
                {#if Array.isArray(value)}
                    {#each value as val, v (v)}
                        {#if val !== ""}
                            <div class="row"><span class="p4">{keyFormatter(key)}</span> = <span class="p5">{val}</span></div>
                        {/if}
                    {/each}
                {:else}
                    <div class="row"><span class="p4">{keyFormatter(key)}</span> = <span class="p5">{value}</span></div>
                {/if}
            {/each}
        {:else}
            {#if parseError}
                <div class="row p2"># {msg("Could not parse config structure. Showing raw text:", "无法解析配置结构，正在显示原始文本：")}</div>
                <div class="row">&nbsp;</div>
            {/if}
            {#each (previewText ?? "").split("\n") as line, i (i)}
                <div class="row">{line}</div>
            {/each}
        {/if}
    </div>

    {#snippet footer()}
        <Button onclick={onclose}>{msg("Dismiss", "关闭")}</Button>
        <Button primary onclick={onimport}>{msg("Import Config", "导入配置")}</Button>
    {/snippet}
</DialogModal>

<style>
.share-modal-desc {
    color: var(--font-color-muted);
    font-size: 0.9rem;
    margin: 0;
    line-height: 1.5;
}

.share-preview {
    background: var(--config-bg);
    font-family: var(--config-font-family);
    font-size: var(--config-font-size);
    color: var(--config-fg);
    overflow-y: auto;
    padding: 8px;
    border-radius: var(--radius-level-3);
    border: 1px solid rgba(0, 0, 0, 0.5);
    box-shadow: 0 0 1px rgba(255, 255, 255, 0.5) inset;
    flex: 1;
    user-select: text;
    min-height: 80px;
    max-height: 280px;
}

.share-preview .row {
    display: block;
    white-space: pre;
}

.p2 {
    color: var(--config-palette-2);
}

.p4 {
    color: var(--config-palette-4);
}

.p5 {
    color: var(--config-palette-5);
}
</style>
