#!/usr/bin/env bun
/**
 * Generates $lib/data/themes.ts from the ghostty/ directory of
 * mbadolato/iTerm2-Color-Schemes.
 *
 * Strategy: sparse-checkout just the `ghostty` folder (single network op,
 * no GitHub API rate limit involved) rather than hitting the contents API
 * once-per-listing and raw.githubusercontent.com once-per-file.
 *
 * Output is a typed TS module (not JSON) so the data becomes part of the
 * build's module graph directly, no runtime fetch + JSON.parse, and the
 * `as const satisfies Record<string, ColorScheme>` type annotation on the
 * export gives a compile-time check that every generated entry actually
 * matches the shape the app expects (catches a malformed entry at build
 * time, not at the point some component reads a missing field at runtime).
 *
 * Each theme file is plain Ghostty config syntax, e.g.:
 *
 *   palette = 0=#1d1f21
 *   palette = 1=#cc6666
 *   ...
 *   background = 282c34
 *   foreground = c5c8c6
 *   cursor-color = c5c8c6
 *   selection-background = 282c34
 *   selection-foreground = c5c8c6
 *
 * This script parses that directly into the `ColorScheme` shape used by
 * $lib/utils/colors.ts, so no dependency on the app's own parse() util is
 * needed here (this runs standalone in CI, not inside the SvelteKit app).
 */

import {execSync} from "node:child_process";
import {mkdtempSync, readdirSync, readFileSync, rmSync, writeFileSync, existsSync, mkdirSync} from "node:fs";
import {tmpdir} from "node:os";
import {join} from "node:path";
import type {HexColor, ColorScheme} from "$lib/utils/colors";


const REPO_URL = "https://github.com/mbadolato/iTerm2-Color-Schemes.git";
const SPARSE_PATH = "ghostty";
const OUTPUT_PATH = join(import.meta.dirname, "..", "src", "lib", "data", "themes.ts");
const SUMMARY_PATH = join(import.meta.dirname, "..", "theme-diff-summary.md");

type ThemeMap = Record<string, ColorScheme>;

function normalizeHex(raw: string): HexColor {
    const trimmed = raw.trim();
    const withHash = trimmed.startsWith("#") ? trimmed : `#${trimmed}`;
    return withHash.toLowerCase() as HexColor;
}

/**
 * Parses a single Ghostty theme file's text content into a ColorScheme.
 * Mirrors the subset of config syntax these generated theme files use:
 * `key = value` lines, with `palette` repeated as `N=#hex` per line.
 *
 * This is basically a highly specialized version of the actual Ghostty
 * config parser that only understands the specific syntax used in these
 * theme files, to can avoid any dependency on the app's own parser and
 * just run this as a standalone script in CI without needing to build
 * the whole SvelteKit app or import its modules.
 */
function parseThemeFile(content: string): ColorScheme {
    const palette: HexColor[] = new Array(256) as HexColor[];
    const scheme: ColorScheme = {palette: []};

    for (const rawLine of content.split("\n")) {
        const line = rawLine.trim();
        if (!line || line.startsWith("#")) continue;

        const eqIndex = line.indexOf("=");
        if (eqIndex === -1) continue;

        const key = line.slice(0, eqIndex).trim();
        const value = line.slice(eqIndex + 1).trim();
        if (!value) continue;

        switch (key) {
            case "palette": {
                const paletteEq = value.indexOf("=");
                if (paletteEq === -1) break;
                const index = parseInt(value.slice(0, paletteEq).trim(), 10);
                const color = value.slice(paletteEq + 1).trim();
                if (!Number.isNaN(index) && index >= 0 && index < 256) {
                    palette[index] = normalizeHex(color);
                }
                break;
            }
            case "background":
                scheme.background = normalizeHex(value);
                break;
            case "foreground":
                scheme.foreground = normalizeHex(value);
                break;
            case "cursor-color":
                scheme.cursorColor = normalizeHex(value);
                break;
            case "cursor-text":
                scheme.cursorText = normalizeHex(value);
                break;
            case "selection-background":
                scheme.selectionBackground = normalizeHex(value);
                break;
            case "selection-foreground":
                scheme.selectionForeground = normalizeHex(value);
                break;
            default:
                break;
        }
    }

    // Trim trailing holes but keep the array dense from 0..highest set index.
    // Most theme files only define indices 0-15; later indices are
    // auto-generated by Ghostty itself (`palette-generate`), so we only
    // emit what the file actually specified.
    let highestSet = -1;
    for (let i = 0; i < palette.length; i++) {
        if (palette[i] !== undefined) highestSet = i;
    }
    scheme.palette = Array.from({length: highestSet + 1}, (_, i) => palette[i] ?? "#000000");

    return scheme;
}

// TODO: Consider switching to Bun.$ instead of `child_process` for the Git commands,
// since it has better support for streaming output and doesn't require a shell, but
// this is simpler for now and works fine.
function sparseCheckout(targetDir: string): void {
    const run = (cmd: string) => execSync(cmd, {cwd: targetDir, stdio: "inherit"});

    mkdirSync(targetDir, {recursive: true});
    run(`git init -q`);
    run(`git remote add origin ${REPO_URL}`);
    run(`git config core.sparseCheckout true`);
    writeFileSync(join(targetDir, ".git", "info", "sparse-checkout"), `${SPARSE_PATH}/*\n`);
    run(`git fetch --depth 1 origin master`);
    run(`git checkout master`);
}

async function main(): Promise<void> {
    const workDir = mkdtempSync(join(tmpdir(), "ghostty-themes-"));

    try {
        console.log(`Cloning sparse checkout of ${SPARSE_PATH}/ into ${workDir}`);
        sparseCheckout(workDir);

        const themeDir = join(workDir, SPARSE_PATH);
        if (!existsSync(themeDir)) {
            throw new Error(`Expected directory ${themeDir} after sparse checkout but it does not exist`);
        }

        const files = readdirSync(themeDir).filter((name) => {
            // The repo's ghostty/ folder is theme files only (no extensions),
            // but skip anything that looks like a dotfile or directory just in case.
            return !name.startsWith(".");
        });

        console.log(`Found ${files.length} theme files`);

        const themes: ThemeMap = {};
        for (const fileName of files) {
            const fullPath = join(themeDir, fileName);
            const content = readFileSync(fullPath, "utf-8");
            try {
                themes[fileName] = parseThemeFile(content);
            }
            catch (err) {
                console.warn(`Skipping "${fileName}": failed to parse (${(err as Error).message})`);
            }
        }

        const sortedThemes: ThemeMap = {};
        for (const name of Object.keys(themes).sort((a, b) => a.localeCompare(b, undefined, {sensitivity: "base", numeric: true}))) {
            sortedThemes[name] = themes[name];
        }

        const previousThemes: ThemeMap = await readPreviousThemes();

        writeSummary(previousThemes, sortedThemes);

        mkdirSync(join(import.meta.dirname, "..", "src", "lib", "data"), {recursive: true});
        writeFileSync(OUTPUT_PATH, renderModule(sortedThemes));

        console.log(`Wrote ${Object.keys(sortedThemes).length} themes to ${OUTPUT_PATH}`);
    }
    finally {
        rmSync(workDir, {recursive: true, force: true});
    }
}

/**
 * Reads back the previously generated module's exported `themes` object,
 * for diffing against the freshly generated set. Returns an empty map if
 * no previous file exists (first run) or it fails to import for any reason
 * (e.g. hand-edited into something that doesn't parse) rather than failing
 * the whole generation, since a missing "previous" state just means
 * everything looks "added" in the summary, which is an acceptable
 * degradation rather than a hard failure.
 */
async function readPreviousThemes(): Promise<ThemeMap> {
    if (!existsSync(OUTPUT_PATH)) return {};

    try {
        // Cache-bust via query param so re-runs in the same process (tests,
        // watch mode) don't get a stale module from Bun's import cache.
        const mod = await import(`${OUTPUT_PATH}?t=${Date.now()}`) as {themes?: ThemeMap;};
        return mod.themes ?? {};
    }
    catch (err) {
        console.warn(`Could not read previous themes module for diffing (${(err as Error).message}); treating as empty`);
        return {};
    }
}

/**
 * Renders the final TS module source: a typed `Record<string, ColorScheme>`
 * const export. Using `JSON.stringify` per-value keeps formatting
 * consistent and avoids hand-rolling object literal serialization, while
 * the surrounding TS gives us the type import + annotation JSON can't.
 */
function renderModule(themes: ThemeMap): string {
    const lines: string[] = [];
    lines.push("// This file is auto-generated by scripts/generate-themes.ts");
    lines.push("// Do not edit directly: changes will be overwritten by the next sync.");
    lines.push("// See .github/workflows/sync-themes.yml for the generation schedule.");
    lines.push("/* eslint-disable quote-props, key-spacing */");
    lines.push("");
    lines.push("import type {ColorScheme} from \"$lib/utils/colors\";");
    lines.push("");
    lines.push("export const themes = {");

    const names = Object.keys(themes);
    for (let i = 0; i < names.length; i++) {
        const name = names[i];
        const entry = JSON.stringify(themes[name]);
        const trailingComma = i < names.length - 1 ? "," : "";
        lines.push(`    ${JSON.stringify(name)}: ${entry}${trailingComma}`);
    }

    lines.push("} as const satisfies Record<string, ColorScheme>;");
    lines.push("");
    lines.push("export default themes;");
    lines.push("");

    return lines.join("\n");
}

/**
 * Writes a human-readable diff summary (added/removed/changed theme names)
 * for use in the PR body. Doesn't diff color values in detail, just whether
 * a theme's serialized form changed at all.
 */
function writeSummary(previous: ThemeMap, next: ThemeMap): void {
    const prevNames = new Set(Object.keys(previous));
    const nextNames = new Set(Object.keys(next));

    const added = [...nextNames].filter((n: string) => !prevNames.has(n)).sort();
    const removed = [...prevNames].filter((n: string) => !nextNames.has(n)).sort();
    const changed = [...nextNames]
        .filter((n: string) => prevNames.has(n) && JSON.stringify(previous[n]) !== JSON.stringify(next[n]))
        .sort();

    const lines: string[] = [];
    lines.push(`### Theme sync summary`);
    lines.push("");
    lines.push(`- **${added.length}** added`);
    lines.push(`- **${removed.length}** removed`);
    lines.push(`- **${changed.length}** changed`);
    lines.push(`- **${nextNames.size}** total themes`);

    if (added.length) {
        lines.push("", "<details><summary>Added</summary>", "");
        for (const name of added) lines.push(`- \`${name}\``);
        lines.push("</details>");
    }

    if (removed.length) {
        lines.push("", "<details><summary>Removed</summary>", "");
        for (const name of removed) lines.push(`- \`${name}\``);
        lines.push("</details>");
    }

    if (changed.length) {
        lines.push("", "<details><summary>Changed</summary>", "");
        for (const name of changed) lines.push(`- \`${name}\``);
        lines.push("</details>");
    }

    writeFileSync(SUMMARY_PATH, lines.join("\n") + "\n");
}

main().catch((err: unknown) => {
    console.error(err);
    process.exit(1);
});