<script lang="ts">
    import Page from "$lib/views/Page.svelte";
    import Group from "$lib/components/settings/Group.svelte";
    import Item from "$lib/components/settings/Item.svelte";
    import Separator from "$lib/components/settings/Separator.svelte";
    import {diff, load} from "$lib/stores/config.svelte";
    import parse from "$lib/utils/parse";

    let pasteConfigText = $state("Clipboard");
    let copyConfigText = $state("Clipboard");


    // TODO: move alert() to real modals
    function loadConfig(candidate: string) {
        let parsed;
        try {
            parsed = parse(candidate);
        }
        catch (parseError) {
            // eslint-disable-next-line no-console
            console.error(parseError);
            alert("Something went wrong trying to parse your config. Please open an issue on GitHub!");
            return;
        }

        try {
            load(parsed);
        }
        catch (loadError) {
            // eslint-disable-next-line no-console
            console.error(loadError);
            alert("Something went wrong trying to load your parsed config. Please open an issue on GitHub!");
            return;
        }
    }

    function pasteConfig() {
        if (pasteConfigText === "Pasted!") return;
        window.navigator.clipboard.readText().then(text => {
            pasteConfigText = "Pasted!";
            setTimeout(() => (pasteConfigText = "Clipboard"), 3000);
            loadConfig(text);
        });
    }

    let filePicker: HTMLInputElement;
    function openFilePicker() {
        filePicker.click();
    }

    function selectFile() {
        const file = filePicker.files![0];
        const reader = new FileReader();
        reader.addEventListener("load", (event) => {
            const loadedText = event.target?.result?.toString();
            if (loadedText) loadConfig(loadedText);
        });
        reader.readAsText(file);
    }

    function copyConfig() {
        if (copyConfigText === "Copied!") return;
        const config = "# Config generated by Ghostty Config\n\n" + Object.entries(diff()).map(e => `${e[0]} = ${e[1]}`).join("\n");
        window.navigator.clipboard.writeText(config).then(() => {
            copyConfigText = "Copied!";
            setTimeout(() => (copyConfigText = "Clipboard"), 3000);
        });
    }

    function downloadConfig() {
        const file = new File(["# Config generated by Ghostty Config\n\n" + Object.entries(diff()).map(e => `${e[0]} = ${e[1]}`).join("\n")], "config", {type: "text/plain"});
        const link = document.createElement("a");
        const url = URL.createObjectURL(file);
        link.href = url;
        link.download = file.name;
        link.style.display = "none";
        document.body.append(link);
        link.click();
        link.remove();
        URL.revokeObjectURL(url);
    }
</script>

<Page title="Import & Export">
    <Group flex={1}>
        <div class="preview">
            <div class="row p2"># You can preview the config here</div>
            <div class="row">&nbsp;</div>

            {#each Object.entries(diff()) as [key, value], i (i)}
                {#if Array.isArray(value)}
                    {#each value as val, v (v)}
                    <div class="row"><span class="p4">{key}</span> = <span class="p5">{val}</span></div>
                    {/each}
                {:else}
                    <div class="row"><span class="p4">{key}</span> = <span class="p5">{value}</span></div>
                {/if}
            {/each}
        </div>
        <Separator />
        <Item name="Import">
            <div class="button-group">
                <button type="button" onclick={pasteConfig}>{pasteConfigText}</button>
                <input id="config-input" type="file" onchange={selectFile} bind:this={filePicker} />
                <button type="button" onclick={openFilePicker}>File...</button>
            </div>
        </Item>
        <Separator />
        <Item name="Export">
            <div class="button-group">
                <button type="button" onclick={copyConfig}>{copyConfigText}</button>
                <button type="button" onclick={downloadConfig}>File...</button>
            </div>
        </Item>
    </Group>
</Page>

<svelte:head>
    <title>Ghostyy Config - Import & Export</title>
</svelte:head>

<style>
.preview {
    background: var(--config-bg);
    font-family: var(--config-font-family);
    font-size: var(--config-font-size);
    color: var(--config-fg);
    min-height: 200px;
    overflow-y: auto;
    padding: 8px;
    border-radius: 8px;
    border: 1px solid rgba(0, 0, 0, 0.5);
    box-shadow: 0 0 1px rgba(255, 255, 255, 0.5) inset;
    flex: 1;
}

.preview .row {
    display: flex;
    white-space: pre;
    flex: 1;
    /* width: 100%; */
    /* overflow: hidden; */
}

/* .bold {font-weight: 700;} */

/* .fg {color: var(--config-fg);} */

/* .p0 {color: var(--config-palette-0);} */
/* .p1 {color: var(--config-palette-1);} */
.p2 {color: var(--config-palette-2);}
/* .p3 {color: var(--config-palette-3);} */
.p4 {color: var(--config-palette-4);}
.p5 {color: var(--config-palette-5);}
/* .p6 {color: var(--config-palette-6);}
.p7 {color: var(--config-palette-7);}
.p8 {color: var(--config-palette-8);}
.p9 {color: var(--config-palette-9);}
.p10 {color: var(--config-palette-10);}
.p11 {color: var(--config-palette-11);}
.p12 {color: var(--config-palette-12);} */
/* .p13 {color: var(--config-palette-13);}
.p14 {color: var(--config-palette-14);}
.p15 {color: var(--config-palette-15);} */


#config-input {
    display: none;
}

.button-group {
    display: flex;
    gap: 12px;
}

/* modal bg #231E2A */
/* TODO: extract to a separate component for usage elsewhere */
button {
    background: #625D67;
    border-radius: 7px;
    border: 0;
    color: inherit;
    padding: 2px 10px;
    font-size: 1.1rem;
    box-shadow: 0 0 1px rgba(0, 0, 0, 0.5);
}

button:active {
    filter: brightness(115%);
}
</style>