// This file is auto-generated by scripts/generate-macicons.ts
// Do not edit directly: changes will be overwritten by the next sync.
// See .github/workflows/macicons.yml for the generation schedule.


export const iconBase = "/macicons";

export const iconUrls = {
    official: `${iconBase}/official.png`,
    blueprint: `${iconBase}/blueprint.png`,
    chalkboard: `${iconBase}/chalkboard.png`,
    microchip: `${iconBase}/microchip.png`,
    glass: `${iconBase}/glass.png`,
    holographic: `${iconBase}/holographic.png`,
    paper: `${iconBase}/paper.png`,
    retro: `${iconBase}/retro.png`,
    xray: `${iconBase}/xray.png`,
} as const satisfies Record<string, string>;

export const frameUrls = {
    aluminum: `${iconBase}/aluminum.png`,
    beige: `${iconBase}/beige.png`,
    plastic: `${iconBase}/plastic.png`,
    chrome: `${iconBase}/chrome.png`,
} as const satisfies Record<string, string>;

export const customLayerUrls = {
    screen: `${iconBase}/screen.png`,
    crt: `${iconBase}/crt.png`,
    gloss: `${iconBase}/gloss.png`,
} as const satisfies Record<string, string>;
